Wojciech Rzeźniczak 209450 - dekorowanie driverów za pomocą observera
iis-powp-2019/powp_jobs2d_development pull request #29
Opened 2019-06-07 23:21 UTC by 209450

2019-06-10 09:52 UTC, kowallus requested changes
Not bad, but probably does not work.

2019-06-10 09:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverDecorator.java
> +public class DriverDecorator {
DriverDecoratorApplicator

2019-06-10 09:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverDecorator.java
> +    public Job2dDriver decorate(Job2dDriver job2dDriver){
change to private and add public method applyDecorationIfStateToDecorate()

2019-06-10 09:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverDecorator.java
> +    public Job2dDriver undoDecorate(Job2dDriver job2dDriver){
fix if necessary

2019-06-10 09:52 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
>  		driver = new LineDriverAdapterUseControl(new LineDriverAdapter(drawerController, LineFactory.getSpecialLine(), "special"));
remove fixed decorator

2019-06-10 09:52 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DriverFeature.java
> +
driverManager.setCurrentDriver (test and fix loop feedback)

2019-06-15 22:55 UTC, 209450 commented
Poprawione

2019-06-21 16:37 UTC, kowallus reviewed
OK. Final lab grade: 3

2019-06-21 16:37 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/DriverDecoratorManager.java
> +    private ArrayList<DriverDecoratorApplicator> listOfDecorators = new ArrayList<>();
Type of attribute should be List (implementation is secondary)

2019-06-21 16:39 UTC, merged